window.QM1_FR_ALL = {
  '2': {
    page: {'.back-link':'← Tous les chapitres','.hero .eyebrow':'MÉTHODES QUANTITATIVES 1 · CHAPITRE 2','.hero h1':'Mesures de tendance centrale','.hero .lead':'Choisir et interpréter la mesure de position centrale appropriée.','.progress-card span':'Votre progression','.access-card .eyebrow':'ACCÈS AUX CORRIGÉS','#accessTitle':'Déverrouiller les corrigés détaillés','.access-card>div>p:last-child':'Utilisez le code de séance communiqué par votre enseignant. L’accès collectif est vérifié automatiquement.','label[for="accessCode"]':'Code de séance','#accessCode@placeholder':'Saisissez le code de séance','#codeForm button':'Déverrouiller'},
    nav:['1 · Moyenne, médiane et mode','2 · Décisions pondérées','3 · Médiane et quartiles groupés','4 · Moyennes géométrique et harmonique','5 · Choisir la mesure centrale'],
    exercises:{
      '1':{level:'NIVEAU 1 : CALCUL DIRECT',title:'Moyenne, médiane et mode',question:`<p>Les temps d’attente sont 4, 5, 5, 6, 7, 8, 9 et 26 minutes. Calculez le mode, la médiane et la moyenne. Quelle mesure décrit le mieux un temps d’attente typique ?</p>`,hint:'Ordonnez les données. Pour huit observations, la médiane est la moyenne des quatrième et cinquième valeurs.',solution:`<h3>Corrigé détaillé</h3><p><strong>Méthode.</strong> Les données sont déjà ordonnées. La médiane est la moyenne des positions 4 et 5 ; la moyenne utilise toutes les observations.</p><p><strong>Résultat.</strong> Mode = 5 ; médiane = (6 + 7)/2 = 6,5 ; moyenne = 70/8 = 8,75 minutes.</p><p><strong>Interprétation.</strong> L’attente isolée de 26 minutes tire la moyenne vers le haut. La médiane est la description la plus robuste d’une attente typique, tandis que la moyenne reste utile pour planifier la capacité totale.</p>`},
      '2':{level:'NIVEAU 2 : CALCUL GUIDÉ',title:'Décisions pondérées',question:`<p>La note d’un cours combine un quiz (20 %), un projet (30 %) et un examen final (50 %). Un étudiant obtient respectivement 14, 16 et 11 sur 20.</p><ol><li>Calculez la moyenne pondérée.</li><li>Comparez-la à la moyenne non pondérée.</li><li>Expliquez pourquoi elles diffèrent.</li></ol>`,hint:'Multipliez chaque note par son poids et vérifiez que la somme des poids vaut 1.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> Moyenne pondérée = 0,20(14) + 0,30(16) + 0,50(11) = 13,10. La moyenne simple est (14 + 16 + 11)/3 = 13,67.</p><p><strong>Interprétation.</strong> L’examen final reçoit le poids le plus élevé et correspond à la note la plus faible ; la moyenne pondérée est donc inférieure.</p>`},
      '3':{level:'NIVEAU 3 : APPLICATION',title:'Médiane et quartiles de données groupées',question:`<p>Les valeurs de commandes sont regroupées ainsi : [0,20[ : 8 ; [20,40[ : 18 ; [40,60[ : 24 ; [60,100[ : 10. Estimez Q1, la médiane et Q3 par interpolation linéaire.</p>`,hint:'Calculez les effectifs cumulés, repérez la classe contenant chaque rang cible, puis interpolez dans cette classe.',solution:`<h3>Corrigé détaillé</h3><p><strong>Méthode.</strong> n = 60 et les effectifs cumulés sont 8, 26, 50 et 60.</p><p><strong>Résultat.</strong> Q1, de rang 15 dans [20,40[, vaut 20 + 20(15−8)/18 = 27,78 €. La médiane, de rang 30 dans [40,60[, vaut 40 + 20(30−26)/24 = 43,33 €. Q3, de rang 45, vaut 40 + 20(45−26)/24 = 55,83 €.</p><p><strong>Interprétation.</strong> Environ la moitié des commandes se situe entre 27,78 € et 55,83 €, sous l’hypothèse d’une répartition uniforme à l’intérieur des classes.</p>`},
      '4':{level:'NIVEAU 3 : CHOIX DE MÉTHODE',title:'Moyennes géométrique et harmonique',question:`<ol><li>Le chiffre d’affaires évolue de +20 %, −10 % puis +15 %. Trouvez le taux de croissance annuel moyen équivalent.</li><li>Un conducteur parcourt deux distances égales à 60 puis 90 km/h. Calculez sa vitesse moyenne.</li></ol>`,hint:'La croissance se compose par multiplication ; pour des distances égales, le temps passé dépend de l’inverse de la vitesse.',solution:`<h3>Corrigé détaillé</h3><p><strong>Méthode.</strong> La croissance composée requiert la moyenne géométrique des facteurs ; des distances égales requièrent la moyenne harmonique des vitesses.</p><p><strong>Résultat.</strong> G = (1,20 × 0,90 × 1,15)^(1/3) = 1,0754, soit 7,54 % par an. H = 2/(1/60 + 1/90) = 72 km/h.</p><p><strong>Interprétation.</strong> Les moyennes arithmétiques, 8,33 % et 75 km/h, ignorent respectivement la composition et les durées de trajet inégales.</p>`},
      '5':{level:'NIVEAU 4 : SYNTHÈSE',title:'Choisir la mesure centrale',question:`<p>Pour chaque situation, choisissez une mesure principale et justifiez-la : salaires avec quelques dirigeants ; taille de produit la plus fréquente ; multiplicateur moyen d’un portefeuille sur quatre ans ; prix moyen lorsque les quantités diffèrent ; catégories de satisfaction ordonnées.</p>`,hint:'Le bon indicateur dépend de la question, du niveau de mesure et du mécanisme de génération des données.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> Salaires : médiane, à cause de l’asymétrie et des valeurs extrêmes. Taille de produit : mode. Multiplicateurs du portefeuille : moyenne géométrique. Prix payé : moyenne arithmétique pondérée par les quantités. Satisfaction : médiane ou mode, accompagnés de la distribution complète.</p><p><strong>Interprétation.</strong> On ne choisit pas une moyenne par habitude : la question et la structure des données déterminent l’indicateur pertinent.</p>`}
    }
  },
  '3': {
    page:{'.back-link':'← Tous les chapitres','.hero .eyebrow':'MÉTHODES QUANTITATIVES 1 · CHAPITRE 3','.hero h1':'Dispersion et concentration','.hero .lead':'Mesurer la variabilité, les inégalités et la concentration.','.progress-card span':'Votre progression','.access-card .eyebrow':'ACCÈS AUX CORRIGÉS','#accessTitle':'Déverrouiller les corrigés détaillés','.access-card>div>p:last-child':'Utilisez le code de séance communiqué par votre enseignant. L’accès collectif est vérifié automatiquement.','label[for="accessCode"]':'Code de séance','#accessCode@placeholder':'Saisissez le code de séance','#codeForm button':'Déverrouiller'},
    nav:['1 · Même moyenne, risque différent','2 · Variance et écart-type','3 · Boîte à moustaches et valeurs atypiques','4 · Dispersion relative','5 · Courbe de Lorenz et indice de Gini'],
    exercises:{
      '1':{level:'NIVEAU 1 : COMPARAISON',title:'Même moyenne, risque différent',question:`<p>Les ventes journalières de l’équipe A sont 48, 49, 50, 51, 52. Celles de l’équipe B sont 30, 40, 50, 60, 70. Comparez leurs moyennes et leurs étendues. Que montre cette comparaison ?</p>`,hint:'Deux séries peuvent avoir le même centre sans avoir la même stabilité.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> Les deux moyennes valent 50. Les étendues valent 52−48 = 4 et 70−30 = 40.</p><p><strong>Interprétation.</strong> Des moyennes égales n’impliquent pas une stabilité égale : l’équipe B est beaucoup plus volatile. Une mesure de position doit être accompagnée d’une mesure de dispersion.</p>`},
      '2':{level:'NIVEAU 2 : CALCUL GUIDÉ',title:'Variance et écart-type',question:`<p>Pour x = (2, 4, 4, 6, 9), calculez la moyenne de population, les écarts, les écarts au carré, la variance et l’écart-type.</p>`,hint:'Construisez un tableau comportant xi, xi − moyenne et (xi − moyenne)².',solution:`<h3>Corrigé détaillé</h3><p><strong>Méthode.</strong> La moyenne est 25/5 = 5. Les écarts sont −3, −1, −1, 1 et 4 ; leurs carrés sont 9, 1, 1, 1 et 16.</p><p><strong>Résultat.</strong> Somme des carrés = 28 ; variance de population = 28/5 = 5,6 ; écart-type = √5,6 = 2,37.</p><p><strong>Interprétation.</strong> Les observations se situent typiquement à environ 2,37 unités de la moyenne, même si l’écart-type n’est pas une distance moyenne littérale.</p>`},
      '3':{level:'NIVEAU 3 : APPLICATION',title:'Boîte à moustaches et valeurs atypiques',question:`<p>Pour une série ordonnée, Q1 = 18, médiane = 24, Q3 = 30, minimum = 10 et maximum = 55. Calculez l’écart interquartile et les bornes de Tukey. La valeur 55 est-elle potentiellement atypique ?</p>`,hint:'EIQ = Q3 − Q1 ; bornes = Q1 − 1,5 EIQ et Q3 + 1,5 EIQ.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> EIQ = 30−18 = 12. Borne inférieure = 18−1,5(12) = 0 ; borne supérieure = 30+1,5(12) = 48. Comme 55 > 48, cette valeur est potentiellement atypique.</p><p><strong>Interprétation.</strong> « Potentiellement » signifie qu’elle mérite une investigation ; elle ne doit pas être supprimée automatiquement.</p>`},
      '4':{level:'NIVEAU 3 : COMPARAISON',title:'Comparer la dispersion relative',question:`<p>Le magasin A réalise 20 000 € de ventes hebdomadaires moyennes avec un écart-type de 3 000 €. Le magasin B réalise 8 000 € avec un écart-type de 1 600 €. Comparez la variabilité absolue et relative.</p>`,hint:'L’écart-type mesure la dispersion absolue ; le coefficient de variation rapporte l’écart-type à la moyenne.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> A a le plus grand écart-type : 3 000 contre 1 600 €. Mais CV(A) = 3 000/20 000 = 15 %, tandis que CV(B) = 1 600/8 000 = 20 %.</p><p><strong>Interprétation.</strong> B est moins variable en euros, mais davantage variable relativement à son niveau de ventes typique.</p>`},
      '5':{level:'NIVEAU 4 : SYNTHÈSE',title:'Courbe de Lorenz et indice de Gini',question:`<p>Cinq ménages disposent de revenus égaux à 10, 10, 20, 20 et 40. Construisez les parts cumulées de population et de revenu, puis calculez l’indice de Gini par la méthode des trapèzes.</p>`,hint:'Le revenu total vaut 100. Comparez la courbe cumulée à la droite d’égalité parfaite.',solution:`<h3>Corrigé détaillé</h3><p><strong>Méthode.</strong> Parts de population : X = (0 ; 0,2 ; 0,4 ; 0,6 ; 0,8 ; 1). Parts cumulées de revenu : Y = (0 ; 0,1 ; 0,2 ; 0,4 ; 0,6 ; 1).</p><p><strong>Résultat.</strong> Les aires des cinq trapèzes sont 0,01 ; 0,03 ; 0,06 ; 0,10 et 0,16. L’aire totale vaut 0,36 et G = 1−2(0,36) = 0,28.</p><p><strong>Interprétation.</strong> L’inégalité est positive mais non extrême. L’indice doit être accompagné du contexte ou de la courbe de Lorenz.</p>`}
    }
  },
  '4': {
    page:{'.back-link':'← Tous les chapitres','.hero .eyebrow':'MÉTHODES QUANTITATIVES 1 · CHAPITRE 4','.hero h1':'Distributions bivariées','.hero .lead':'Décrire et interpréter les relations entre deux variables.','.progress-card span':'Votre progression','.access-card .eyebrow':'ACCÈS AUX CORRIGÉS','#accessTitle':'Déverrouiller les corrigés détaillés','.access-card>div>p:last-child':'Utilisez le code de séance communiqué par votre enseignant. L’accès collectif est vérifié automatiquement.','label[for="accessCode"]':'Code de séance','#accessCode@placeholder':'Saisissez le code de séance','#codeForm button':'Déverrouiller'},
    nav:['1 · Lire une relation','2 · Covariance et corrélation','3 · Régression par moindres carrés','4 · R², interpolation et extrapolation','5 · De l’association à la décision'],
    exercises:{
      '1':{level:'NIVEAU 1 : LECTURE GRAPHIQUE',title:'Lire une relation',question:`<p>Un nuage de points entre dépenses publicitaires et ventes est croissant. Les points sont proches d’une droite, sauf une observation éloignée.</p><ol><li>Décrivez la direction, la forme et l’intensité.</li><li>Que faut-il examiner concernant le point éloigné ?</li><li>Le graphique prouve-t-il que la publicité cause les ventes ?</li></ol>`,hint:'Décrivez ce qui est visible avant toute interprétation causale.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> La direction est positive, la forme approximativement linéaire et l’association paraît forte. Le point éloigné peut être une erreur, une campagne inhabituelle ou une observation influente ; il faut le vérifier et comparer les résultats avec et sans lui.</p><p><strong>Interprétation.</strong> Le graphique ne prouve pas la causalité : la saisonnalité, la qualité du produit ou une causalité inverse peuvent influencer les deux variables.</p>`},
      '2':{level:'NIVEAU 2 : CALCUL GUIDÉ',title:'Covariance et corrélation',question:`<p>Pour x = (1, 2, 3, 4) et y = (2, 3, 5, 6), calculez la covariance de population et la corrélation.</p>`,hint:'Calculez les deux moyennes, les produits des écarts et les sommes des écarts au carré.',solution:`<h3>Corrigé détaillé</h3><p><strong>Méthode.</strong> Moyennes : 2,5 et 4. Les produits croisés totalisent 7 ; les sommes des carrés valent 5 pour x et 10 pour y.</p><p><strong>Résultat.</strong> Cov(x,y) = 7/4 = 1,75 ; σx = √(5/4) = 1,118 ; σy = √(10/4) = 1,581 ; r = 1,75/(1,118 × 1,581) = 0,990.</p><p><strong>Interprétation.</strong> L’association linéaire positive est très forte. La corrélation, sans unité, est plus facile à comparer que la covariance.</p>`},
      '3':{level:'NIVEAU 3 : APPLICATION',title:'Régression par moindres carrés',question:`<p>À partir des données de l’exercice 2, estimez ŷ = a + bx. Prévoyez y pour x = 3,5 et calculez le résidu au point (3,5).</p>`,hint:'La pente est covariance(x,y)/variance(x), puis l’ordonnée à l’origine est moyenne(y) − b moyenne(x).',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> b = 1,75/1,25 = 1,4 et a = 4−1,4(2,5) = 0,5. Ainsi ŷ = 0,5 + 1,4x. Pour x = 3,5, ŷ = 5,4. Pour x = 3, ŷ = 4,7 ; le résidu vaut 5−4,7 = 0,3.</p><p><strong>Interprétation.</strong> Une hausse d’une unité de x est associée à une hausse estimée de 1,4 unité de y dans le domaine observé.</p>`},
      '4':{level:'NIVEAU 3 : INTERPRÉTATION',title:'R², interpolation et extrapolation',question:`<p>Un modèle estimé pour des budgets publicitaires de 1 000 € à 10 000 € possède R² = 0,81. Interprétez R². Classez les prévisions pour 7 000 € et 20 000 €, puis expliquez le risque.</p>`,hint:'Une prévision située dans l’intervalle observé est une interpolation ; au-delà, il s’agit d’une extrapolation.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> Le modèle explique 81 % de la variation observée des ventes autour de leur moyenne ; cela ne signifie pas que la publicité cause 81 % des ventes. 7 000 € relève de l’interpolation, 20 000 € de l’extrapolation.</p><p><strong>Interprétation.</strong> L’extrapolation est risquée : la relation linéaire peut ne pas se prolonger et une saturation du marché peut apparaître.</p>`},
      '5':{level:'NIVEAU 4 : SYNTHÈSE',title:'De l’association à la décision',question:`<p>Un distributeur observe r = 0,85 entre remises et ventes hebdomadaires et recommande des remises élevées permanentes. Formulez une réponse statistiquement responsable comportant au moins quatre vérifications.</p>`,hint:'La décision dépend de la causalité, des marges, des variables confondantes et de la stabilité de la relation.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> Examiner le nuage pour les non-linéarités et points influents ; analyser les résidus ; contrôler jours fériés, publicité et différences entre magasins ; vérifier si les remises visaient les semaines faibles ; distinguer chiffre d’affaires et profit ; utiliser si possible une expérience randomisée ou une stratégie quasi expérimentale crédible.</p><p><strong>Interprétation.</strong> Une forte corrélation aide à prévoir dans le cadre observé, mais ne suffit pas pour décider d’une politique de prix.</p>`}
    }
  },
  '5': {
    page:{'.back-link':'← Tous les chapitres','.hero .eyebrow':'MÉTHODES QUANTITATIVES 1 · CHAPITRE 5','.hero h1':'Séries temporelles','.hero .lead':'Lire les évolutions dans le temps et distinguer tendance et fluctuations.','.progress-card span':'Votre progression','.access-card .eyebrow':'ACCÈS AUX CORRIGÉS','#accessTitle':'Déverrouiller les corrigés détaillés','.access-card>div>p:last-child':'Utilisez le code de séance communiqué par votre enseignant. L’accès collectif est vérifié automatiquement.','label[for="accessCode"]':'Code de séance','#accessCode@placeholder':'Saisissez le code de séance','#codeForm button':'Déverrouiller'},
    nav:['1 · Composantes et modèles','2 · Moyennes mobiles','3 · Tendance linéaire','4 · Prévision saisonnière multiplicative','5 · Évaluation des prévisions'],
    exercises:{
      '1':{level:'NIVEAU 1 : RECONNAISSANCE',title:'Composantes et modèles',question:`<p>Identifiez tendance, saisonnalité, cycle ou irrégulier dans chaque cas : croissance durable du commerce électronique ; pics de ventes en décembre ; mouvements liés aux récessions ; panne informatique d’une journée. Quand privilégier un modèle multiplicatif ?</p>`,hint:'Demandez-vous si le phénomène est durable, périodique, lié au cycle économique ou exceptionnel.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> Croissance à long terme : tendance ; pics récurrents de décembre : saisonnalité ; mouvements de récession : cycle ; panne : composante irrégulière. Un modèle multiplicatif convient lorsque l’amplitude saisonnière augmente avec le niveau de la série ; un modèle additif convient si les effets absolus restent approximativement constants.</p>`},
      '2':{level:'NIVEAU 2 : LISSAGE',title:'Moyennes mobiles',question:`<p>La demande mensuelle sur cinq mois vaut 90, 105, 99, 120 et 126. Calculez les moyennes mobiles centrées sur trois périodes pour les mois 2, 3 et 4.</p>`,hint:'Calculez la moyenne de chaque fenêtre de trois observations et affectez-la au mois central.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> MM2 = (90+105+99)/3 = 98 ; MM3 = (105+99+120)/3 = 108 ; MM4 = (99+120+126)/3 = 115.</p><p><strong>Interprétation.</strong> Le lissage révèle un mouvement sous-jacent croissant et réduit le bruit mensuel. Les extrémités sont perdues car une fenêtre centrée nécessite des voisins.</p>`},
      '3':{level:'NIVEAU 3 : APPLICATION',title:'Tendance linéaire',question:`<p>Pour t = 1, 2, 3, 4 et Y = (52, 57, 61, 66), estimez Ŷt = a + bt par moindres carrés et prévoyez t = 5.</p>`,hint:'Utilisez les écarts à la moyenne de t et de Y pour calculer la pente.',solution:`<h3>Corrigé détaillé</h3><p><strong>Méthode.</strong> Moyennes : 2,5 et 59. La somme des produits croisés vaut 23 et la somme des carrés de t vaut 5.</p><p><strong>Résultat.</strong> b = 4,6 et a = 59−4,6(2,5) = 47,5. Donc Ŷt = 47,5 + 4,6t et Ŷ5 = 70,5.</p><p><strong>Interprétation.</strong> La tendance ajustée progresse de 4,6 unités par période ; la prévision suppose l’absence de rupture structurelle.</p>`},
      '4':{level:'NIVEAU 3 : PRÉVISION',title:'Prévision saisonnière multiplicative',question:`<p>La tendance trimestrielle est Tt = 100 + 3t. Les coefficients saisonniers sont 0,80 ; 1,05 ; 0,95 ; 1,20 pour T1 à T4.</p><ol><li>Vérifiez la normalisation.</li><li>Prévoyez t = 9, 10, 11 et 12.</li><li>Interprétez le coefficient de T4.</li></ol>`,hint:'Les coefficients doivent avoir une moyenne égale à 1. Multipliez ensuite la tendance par le coefficient du trimestre.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> (0,80+1,05+0,95+1,20)/4 = 1. Les tendances sont 127, 130, 133 et 136. Les prévisions sont 101,6 ; 136,5 ; 126,35 et 163,2.</p><p><strong>Interprétation.</strong> T4 est attendu 20 % au-dessus de la tendance, et non 20 points de pourcentage au-dessus du trimestre précédent.</p>`},
      '5':{level:'NIVEAU 4 : ÉVALUATION',title:'Évaluation des prévisions',question:`<p>Les valeurs réelles sont 100, 120, 110 et 130. Le modèle A prévoit 98, 118, 115 et 128 ; le modèle B prévoit 105, 112, 108 et 140. Calculez la MAE des deux modèles et recommandez-en un. Que faut-il encore vérifier ?</p>`,hint:'La MAE est la moyenne des valeurs absolues des erreurs.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> Erreurs absolues de A : 2, 2, 5, 2 ; MAE(A) = 2,75. Pour B : 5, 8, 2, 10 ; MAE(B) = 6,25. A est préférable selon la MAE.</p><p><strong>Interprétation.</strong> La comparaison doit utiliser une véritable période de validation et examiner aussi le biais, les erreurs en pourcentage, la structure des résidus et les performances après rupture structurelle.</p>`}
    }
  },
  '6': {
    page:{'.back-link':'← Tous les chapitres','.hero .eyebrow':'MÉTHODES QUANTITATIVES 1 · CHAPITRE 6','.hero h1':'Nombres-indices','.hero .lead':'Construire et interpréter les indices de prix, de quantité et de valeur.','.progress-card span':'Votre progression','.access-card .eyebrow':'ACCÈS AUX CORRIGÉS','#accessTitle':'Déverrouiller les corrigés détaillés','.access-card>div>p:last-child':'Utilisez le code de séance communiqué par votre enseignant. L’accès collectif est vérifié automatiquement.','label[for="accessCode"]':'Code de séance','#accessCode@placeholder':'Saisissez le code de séance','#codeForm button':'Déverrouiller'},
    nav:['1 · Indice élémentaire et changement de base','2 · Valeur, Laspeyres et Paasche','3 · Fisher et réversibilité des facteurs','4 · Base fixe, chaînage et déflation','5 · Tableau de bord fournisseur'],
    exercises:{
      '1':{level:'NIVEAU 1 : CALCUL DIRECT',title:'Indice élémentaire et changement de base',question:`<p>Le prix d’un service passe de 40 € en 2023 à 46 € en 2025.</p><ol><li>Calculez l’indice 2025 avec 2023 = 100 et la variation en pourcentage.</li><li>Une ancienne série vaut 90, 100 et 108 pour 2022–2024 avec 2023 = 100. Rebasez-la en 2022 = 100.</li></ol>`,hint:'Un indice élémentaire compare une valeur à sa base. Pour rebaser, divisez tous les indices par l’indice de la nouvelle année de base.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> I = 46/40 × 100 = 115 : le prix augmente de 15 %. Pour rebaser, on divise par 90 et on multiplie par 100 : 100,00 ; 111,11 ; 120,00.</p><p><strong>Interprétation.</strong> Le changement de base modifie la référence, pas les évolutions relatives sous-jacentes.</p>`},
      '2':{level:'NIVEAU 2 : INDICES PONDÉRÉS',title:'Valeur, Laspeyres et Paasche',question:`<div class="table-wrap"><table><thead><tr><th>Produit</th><th>p0</th><th>q0</th><th>p1</th><th>q1</th></tr></thead><tbody><tr><td>A</td><td>2</td><td>100</td><td>2,5</td><td>90</td></tr><tr><td>B</td><td>5</td><td>40</td><td>6</td><td>50</td></tr></tbody></table></div><p>Calculez l’indice de valeur ainsi que les indices de prix de Laspeyres et de Paasche.</p>`,hint:'Calculez les quatre agrégats p0q0, p1q1, p1q0 et p0q1 avant de former les rapports.',solution:`<h3>Corrigé détaillé</h3><p><strong>Méthode.</strong> Σp0q0 = 400 ; Σp1q1 = 525 ; Σp1q0 = 490 ; Σp0q1 = 430.</p><p><strong>Résultat.</strong> Indice de valeur = 525/400 × 100 = 131,25 ; Laspeyres = 490/400 × 100 = 122,50 ; Paasche = 525/430 × 100 = 122,09.</p><p><strong>Interprétation.</strong> La valeur augmente de 31,25 %, tandis que les deux mesures indiquent environ 22 % d’inflation. Elles diffèrent parce qu’elles utilisent les quantités de périodes différentes.</p>`},
      '3':{level:'NIVEAU 3 : DÉCOMPOSITION',title:'Fisher et réversibilité des facteurs',question:`<p>À partir de l’exercice 2, calculez l’indice des prix de Fisher, les indices de quantité de Laspeyres et Paasche, l’indice de quantité de Fisher, puis vérifiez la réversibilité des facteurs.</p>`,hint:'Fisher est la moyenne géométrique de Laspeyres et Paasche. Le produit des indices de prix et de quantité doit retrouver l’indice de valeur.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> Fisher-prix = √(122,50 × 122,09) = 122,30. Laspeyres-quantité = 430/400 × 100 = 107,50 ; Paasche-quantité = 525/490 × 100 = 107,14 ; Fisher-quantité = 107,32. Enfin 122,30 × 107,32/100 = 131,25, à l’arrondi près.</p><p><strong>Interprétation.</strong> Fisher fournit une décomposition symétrique de la variation de valeur en composantes prix et quantité.</p>`},
      '4':{level:'NIVEAU 3 : APPLICATION',title:'Base fixe, chaînage et déflation',question:`<p>Un indice vaut 100 l’année 0 et 110 l’année 1. L’indice-chaîne de l’année 2 par rapport à l’année 1 vaut 106. Le chiffre d’affaires nominal de l’année 2 est 636 000 €.</p><ol><li>Construisez l’indice chaîné de l’année 2.</li><li>Déflatez le chiffre d’affaires en euros de l’année 0.</li></ol>`,hint:'Chaînez les indices par multiplication, puis divisez la valeur nominale par le facteur d’indice.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> Indice chaîné = 110 × 106/100 = 116,6. Chiffre d’affaires réel = 636 000/(116,6/100) ≈ 545 455 €.</p><p><strong>Interprétation.</strong> On divise le montant nominal par le facteur d’indice ; on ne lui retranche pas simplement 16,6 %.</p>`},
      '5':{level:'NIVEAU 4 : SYNTHÈSE',title:'Décision à partir d’un tableau de bord fournisseur',question:`<p>Un acheteur présente : indice de valeur 128, indice des prix de Fisher 120 et indice des quantités de Fisher 106,67. Expliquez ces nombres, vérifiez leur cohérence et donnez deux précautions avant d’attribuer la hausse des prix au pouvoir de marché du fournisseur.</p>`,hint:'Vérifiez la relation valeur = prix × quantité, puis distinguez description statistique et explication causale.',solution:`<h3>Corrigé détaillé</h3><p><strong>Résultat.</strong> Les dépenses dépassent la base de 28 %, les prix d’environ 20 % et les quantités d’environ 6,67 %. La cohérence est vérifiée : 120 × 106,67/100 ≈ 128.</p><p><strong>Interprétation.</strong> L’indice reste descriptif. Avant de conclure au pouvoir de marché, examiner la qualité et la composition des produits, les clauses contractuelles, les coûts des intrants, les taux de change, la couverture du panier et la représentativité des pondérations.</p>`}
    }
  }
};
